"""empty message

Revision ID: 64ec42007400
Revises: 4c1cfe4d1c3c
Create Date: 2025-02-05 15:31:40.845916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64ec42007400'
down_revision = '4c1cfe4d1c3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=32), nullable=False))
        batch_op.add_column(sa.Column('name', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('lastname', sa.String(length=32), nullable=True))
        batch_op.create_unique_constraint(None, ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('lastname')
        batch_op.drop_column('name')
        batch_op.drop_column('username')

    # ### end Alembic commands ###
